CREATE DATABASE istatus;

CREATE TABLE statuses ( 
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Author VARCHAR(255) NOT NULL,
	Message VARCHAR(1000) NOT NULL,
	PhotoUrl VARCHAR(1000) NULL,
	Datetime VARCHAR(100) NOT NULL 
);